// Static data + brand tokens for the sign-up wizard, extracted from SignUpForm.tsx.
import type { AccountValidationField } from "./types";

export const BRAND_DARK = "#1a312c";
export const BRAND_INK = "#0f1c18";
export const BRAND_MID = "#428475";
export const BRAND_MINT = "#89d7b7";

export const SKILLS = [
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "FastAPI",
  "AI/ML",
  "PostgreSQL",
  "AWS",
  "Docker",
  "Solidity",
  "TypeScript",
  "JavaScript",
  "Vue",
  "Angular",
  "Svelte",
  "React Native",
  "Flutter",
  "Swift",
  "Kotlin",
  "Java",
  "C#",
  ".NET",
  "Go",
  "Rust",
  "PHP",
  "Laravel",
  "Ruby on Rails",
  "Django",
  "Flask",
  "Express",
  "NestJS",
  "GraphQL",
  "MongoDB",
  "MySQL",
  "Redis",
  "Firebase",
  "Supabase",
  "Azure",
  "Google Cloud",
  "Kubernetes",
  "Terraform",
  "CI/CD",
  "DevOps",
  "Data Engineering",
  "TensorFlow",
  "PyTorch",
  "OpenAI API",
  "UI/UX",
  "Figma",
  "Three.js",
  "Unity",
  "Unreal Engine",
  "Blockchain",
  "Smart Contracts",
];
export const PRIMARY_GOALS = [
  "Turn my idea into a structured startup blueprint",
  "Find and hire developers to build my product",
  "Get my startup in front of investors",
  "Test and validate my startup concept",
];
export const EDUCATION_LEVELS = [
  "Student",
  "Intermediate / Higher Secondary",
  "Diploma",
  "Undergraduate",
  "Bachelor's",
  "Master's",
  "MBA",
  "MPhil",
  "PhD / Doctorate",
  "Professional Certification",
  "Self-taught / Bootcamp",
  "Prefer not to say",
  "Other",
];
export const DEGREE_OPTIONS_BY_LEVEL: Record<string, string[]> = {
  Student: ["Currently studying", "No formal degree yet", "Other"],
  "Intermediate / Higher Secondary": [
    "High School / Secondary School",
    "Intermediate / FSc",
    "Intermediate / FA",
    "A-Levels",
    "GED / Equivalent",
    "Other",
  ],
  Diploma: [
    "Diploma in Business",
    "Diploma in Computer Science",
    "Diploma in Information Technology",
    "Diploma in Engineering",
    "Diploma in Design",
    "Associate Degree",
    "Other",
  ],
  Undergraduate: [
    "Undergraduate - Business",
    "Undergraduate - Computer Science",
    "Undergraduate - Engineering",
    "Undergraduate - Arts",
    "Undergraduate - Medicine",
    "Undergraduate - Law",
    "Other",
  ],
  "Bachelor's": [
    "BA",
    "BSc",
    "BBA",
    "BCom",
    "BS Computer Science",
    "BS Software Engineering",
    "BS Information Technology",
    "BS Data Science",
    "BS Artificial Intelligence",
    "BS Cybersecurity",
    "BS Electrical Engineering",
    "BS Mechanical Engineering",
    "BS Civil Engineering",
    "BS Biomedical Engineering",
    "BEng / BE",
    "BTech",
    "BArch",
    "BFA",
    "LLB",
    "MBBS",
    "BDS",
    "Pharm-D",
    "BEd",
    "Other",
  ],
  "Master's": [
    "MA",
    "MSc",
    "MCom",
    "MEd",
    "MS Computer Science",
    "MS Software Engineering",
    "MS Data Science",
    "MS Artificial Intelligence",
    "MS Cybersecurity",
    "MS Electrical Engineering",
    "MS Mechanical Engineering",
    "MEng / ME",
    "MPH",
    "LLM",
    "Other",
  ],
  MBA: [
    "MBA",
    "Executive MBA",
    "MBA Finance",
    "MBA Marketing",
    "MBA Entrepreneurship",
    "MBA Technology Management",
    "Other",
  ],
  MPhil: [
    "MPhil",
    "MPhil Computer Science",
    "MPhil Business",
    "MPhil Economics",
    "MPhil Education",
    "MPhil Psychology",
    "Other",
  ],
  "PhD / Doctorate": [
    "PhD",
    "DBA",
    "EdD",
    "MD",
    "Doctorate in Engineering",
    "Doctorate in Computer Science",
    "Other",
  ],
  "Professional Certification": [
    "CA",
    "ACCA",
    "CFA",
    "CPA",
    "PMP",
    "AWS Certification",
    "Google Certification",
    "Microsoft Certification",
    "Other",
  ],
  "Self-taught / Bootcamp": [
    "Self-taught",
    "Coding Bootcamp",
    "Design Bootcamp",
    "Founder Fellowship",
    "Online Certification",
    "Other",
  ],
  "Prefer not to say": ["Prefer not to say"],
  Other: ["Other"],
};

export const DEFAULT_DEGREE_OPTIONS = ["Select education level first"];

export const COUNTRIES_STATES_URL = "https://countriesnow.space/api/v0.1/countries/states";
export const COUNTRY_CODES_URL = "https://countriesnow.space/api/v0.1/countries/codes";
export const STATE_CITIES_URL = "https://countriesnow.space/api/v0.1/countries/state/cities";
export const COUNTRY_CITIES_URL = "https://countriesnow.space/api/v0.1/countries/cities";
export const NO_REGION = "Not applicable";

export const ACCOUNT_FIELD_LABELS: Record<AccountValidationField, string> = {
  firstName: "First name",
  lastName: "Last name",
  email: "Email",
  confirmEmail: "Confirm email",
  password: "Password",
  confirmPassword: "Confirm password",
  country: "Country",
  countryCode: "Country code",
  stateProvince: "State / Province",
  city: "City",
  phone: "Phone number",
  dob: "Date of birth",
  terms: "Terms and Privacy Policy agreement",
};

export const REQUIRED_ACCOUNT_FIELDS = new Set<AccountValidationField>([
  "firstName",
  "lastName",
  "email",
  "confirmEmail",
  "password",
  "confirmPassword",
  "country",
  "countryCode",
  "stateProvince",
  "city",
  "phone",
  "dob",
  "terms",
]);
