// Developer profile default, extracted from the DeveloperDashboard view.
import type { DeveloperProfile } from "@/features/developer-dashboard/profile-utils";

export const DEFAULT_DEVELOPER_PROFILE: DeveloperProfile = {
  firstName: "",
  lastName: "",
  email: "",
  phone: "",
  phoneVerified: false,
  avatarUrl: "",
  jobTitle: "",
  role: "",
  bio: "",
  tags: [],
  skillEntries: [],
  techStack: [],
  education: "",
  educationLevel: "",
  degreeName: "",
  degreeSelection: "",
  customDegreeName: "",
  educations: [],
  github: "",
  linkedin: "",
  portfolioLink: "",
  certifications: [],
  stripeAccountId: "",
  stripeOnboardingComplete: false,
  stripeChargesEnabled: false,
  stripePayoutsEnabled: false,
  profileComplete: false,
  firstTime: false,
};
