"""add_skills_tags_domains

Revision ID: 56521dc74bd8
Revises: 
Create Date: 2026-07-08 11:56:28.427772
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '56521dc74bd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('founder', 'developer', name='user_role'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('state_province', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('developer_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.SmallInteger(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('open_to_remote', sa.Boolean(), nullable=False),
    sa.Column('preferred_budget', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('portfolio_link', sa.String(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(), nullable=False),
    sa.Column('profile_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('founder_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('venture_stage', sa.String(), nullable=True),
    sa.Column('primary_goal', sa.String(), nullable=False),
    sa.Column('profile_complete', sa.Boolean(), nullable=False),
    sa.Column('stripe_connected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.Enum('Skill', 'Tech stack', 'Framework', 'Tool', name='skill_kind'), nullable=False),
    sa.Column('experience_level', sa.Enum('Learning', '< 1 year', '1-2 years', '3-5 years', '5+ years', name='skill_experience'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', 'kind', name='uq_user_skill_kind')
    )
    op.create_table('developer_tags',
    sa.Column('developer_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('developer_id', 'tag_id')
    )
    op.create_table('founder_domains',
    sa.Column('founder_id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['founder_id'], ['founder_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('founder_id', 'domain_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('founder_domains')
    op.drop_table('developer_tags')
    op.drop_table('user_skills')
    op.drop_table('founder_profiles')
    op.drop_table('developer_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
